application_data_volume:
    image: 'busybox'
    tty: true
    restart: 'always'
    container_name: 'application_data_volume'
    volumes:
      - './www/:/var/www/'

php-cli:
    build: 'php-cli/php70'
    container_name: 'php-cli'
    volumes:
        - './shared/composer/:/root/.composer/'
    volumes_from:
        - application_data_volume
    working_dir: /var/www

turbine:
    build: 'php-cli/php70'
    volumes_from:
        - application_data_volume
    working_dir: /var/www
    command: ./vendor/bin/ppm start --socket-path /tmp/ppm --max-requests 100
    restart: always
    expose:
        - 1337
    labels:
      - "traefik.backend=turbine"
      - "traefik.frontend.rule=Host:turbine.docker.localhost"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.weight=10"
      - "Host:{containerName}.{domain}"

neo4j:
    image: neo4j:3.0
    expose:
        - 7474:7474
    ports:
        - 7687:7687
    volumes:
        - ./shared/neo4j/data:/data

tolerance_viewer_api:
    image: 'sroze/tolerance-viewer-api'
    environment:
        NEO4J_HOST: 'neo4j'
        NEO4J_PORT: '7474'
        NEO4J_USERNAME: 'neo4j'
        NEO4J_PASSWORD: 'admin'
    expose:
        - 80
    links:
        - neo4j
    labels:
        - "traefik.backend=tolerance-api"
        - "traefik.frontend.rule=Host:tolerance.api.docker.localhost"
        - "Host:{containerName}.{domain}"

tolerance_viewer_ui:
    image: 'sroze/tolerance-viewer-ui'
    environment:
        UI_PORT: 80
        API_ROOT: http://tolerance.api.docker.localhost
    expose:
      - 80
    labels:
        - "traefik.backend=tolerance"
        - "traefik.frontend.rule=Host:tolerance.ui.docker.localhost"
        - "Host:{containerName}.{domain}"

traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
        - "80:80"
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /dev/null:/traefik.toml

